language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  - ./gradlew coveralls
  - ./gradlew sonarqube

deploy:
  provider: heroku
  api_key:
    secure: "U1O5Hx3z4WNTLs3EF3mHxhOuFyLrnadeWnF5d8QJ8VWv3eXq7EpAUox84kxg3dwMhOqe6g5C2xlchQVqoc6OXpAjMvvsPiuNQXW+l68uILGws6aXDdxunyO6nWZYmx1hHLsRCIEjK5J3uqzReM6Xr7Q2FwB8m4uMI7CHaalxDnzTGmDcl3IIONEuEYQnIn3wmbiC11F4V9wph9hlWSa8Q88+HO9Bu3yEcVCj3ISTiIzvkOaA40RkDdsLdBzHZSm8KV7eNDudMEkN6KHvsx0ywGH9yOYcud8jjfguFMlcC+JvaiR4B7C/DTM8LVRh0Mz+Filojbo6OQ7aV2r95klm1VIZe6RDbU4Lj2S6HYwEdSwfP7+5RfcmvXXRKZ13077lr9JUGQuIA2Wv+elK3CellHQXC1pO3YNkGR8OoGQRwpGTiMn4a75g3uwBlFVdF/lxZL+bv15inPSr2b/wWTUFSRypvi9ljbpozeAhKcluglX61wgvoNEDUNILl4EZ2CyBEGGLWMtpRow8XCZjpDdB5Y/KOfRKt7U6G0dQ27C/GIzuCbGjVkzXgtscUWqfsLnyX247Nmy4antT7iWsEtX1NOHD/nb0Xqr4pgJ0YdHDfr0uCeJBciZeF+4sY6giwVgfWusqjJT1K5vHWXPLmvPp0+xp996H1eVIisn7LREFEd8="
  app:
    master: hyness-video-search
    develop: hyness-video-search-develop

addons:
  sonarcloud:
    organization: hyness
    token:
      secure: "nph6j5IvwWlEabYA2fyY1/ZlqUA5xN5zQsJY7uB9AQ3J7Z1fEmDfrqt7BxiBzSTW1BJk0OUv7PVxcf+p9RH3saw6Ghh4flC4RPj0WtWxjGo9iHyciXin6Yb5ylp7wUsvVfXiLdyZmPQxe5iO8Omq3Z7Y8PnRSNmhdh+hmybofduGPCYvXYhEQ7DJQVBQQdLPq8+hnm15tpnVz+2msWZYhrYnGmwEsC35b+gtjKaE3dnm5VZpDgCL/8dFwOI1+sWiEIVCVSgM2vSN9GrH6mzq9hMY5WXD3pL9B+ispLChWplAN1fzpl/WwlWe9SMpB9Z4bf9hMHUV2QPJ9LxYEfvK1OYKnzVIaNouSwrAF8jS1lYElsqhtQM9aFIP+YJUfpF8jfzEtKx8ZNebjf8CjliwLXpAq9xFtFAZKOqZm7zqINBmZ2ONgZnMFak0OoqRdhGmDBy+KS5X/nGddkJqHUu6CkJz7C05xXnVbUpc5NRZ6c5KMAB5ZICnlplFLXK3aafcIIwe9eS5E2qdSf7wnikrcbNgIS+NLI2fwgpR9mxgO0QgqQDD9E3ga/yit8ZVLlw0MMZu2PRablOXSFG6qOD6TySyGgNluin8xjufDLNg3tTQF3WT/H+30iChu53kbnRReBZGQtuKWk1jQq6ZdVZJ720PfQIJrW1S7+vT570QXTQ="
