sudo: required

language: java

env:
  - APP_ENV=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo $TRAVIS_BRANCH; else echo develop; fi)

services:
  - docker

jdk:
  - openjdk11

install: skip

before_script:
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_AUTH_TOKEN registry.heroku.com

script:
  - ./gradlew build --continue
  - docker build -t registry.heroku.com/$HEROKU_APP-$APP_ENV/web .

after_success:
  - ./gradlew jacocoTestReport coveralls
  - docker push registry.heroku.com/$HEROKU_APP-$APP_ENV/web
