youtube-service:
  api-key: ${key}
  search-url: https://www.googleapis.com/youtube/v3/search?q={term}&type=video&videoDefinition={videoDefinition}&pageToken={pageToken}&maxResults={maxResults}&key={key}&part=snippet&relevanceLanguage=en

security:
    ignored:
        - /*
        - /styles/**
        - /js/**
        - /img/**
        - /search/**
        - /webjars/**
---
spring:
  profiles: dev

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---
spring:
  profiles: prod

management:
    context-path: /manage
